// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSP.Data;

#nullable disable

namespace OSP.Migrations
{
    [DbContext(typeof(OSPContext))]
    [Migration("20240123234840_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("OSP.Models.Drive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DriveId")
                        .HasColumnType("int");

                    b.Property<int>("FirefighterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriveId");

                    b.HasIndex("FirefighterId");

                    b.ToTable("Drive");
                });

            modelBuilder.Entity("OSP.Models.Firefighter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataS")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Driver")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Firefighter");
                });

            modelBuilder.Entity("OSP.Models.Drive", b =>
                {
                    b.HasOne("OSP.Models.Drive", null)
                        .WithMany("Drives")
                        .HasForeignKey("DriveId");

                    b.HasOne("OSP.Models.Firefighter", "Firefighter")
                        .WithMany()
                        .HasForeignKey("FirefighterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firefighter");
                });

            modelBuilder.Entity("OSP.Models.Drive", b =>
                {
                    b.Navigation("Drives");
                });
#pragma warning restore 612, 618
        }
    }
}
